### ISSUE TITLE
Add @SaveState support for the RecyclerView

### ISSUE THREAD

**Issue by brianwernick** [hansenji/pocketknife#10]
It would be nice to be able to annotate a RecyclerView with @SaveState in order to persist the scroll location and other information about the view.  

Currently you have to manually grab the LayoutManager and save the instance to a bundle
```java
recyclerView.getLayoutManager().onSaveInstanceState()
```
Performing the reverse when restoring the state
```java
recyclerView.getLayoutManager().onRestoreInstanceState();
```

**Comment by hansenji** [comment]
Sorry this is taking so long, I am excited about the solution for this hopefully I will finish in the next day or two.
