### ISSUE TITLE
ClassCastException: PackageSymbol cannot be cast to TypeElement

### ISSUE THREAD

**Issue by pushbit** [hansenji/pocketknife#13]
I added one `@SaveState` field and then got the following compile error.

Error:Execution failed for task ':lib:compileReleaseJavaWithJavac'.
> java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$PackageSymbol cannot be cast to javax.lang.model.element.TypeElement
pendency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

I tried the suggested remedies, but none of them changed anything.  I checked the cached jars and they appeared to be ok.  I re-synced the project.  I restarted all java/gradle processes.  I am using another annotation processor (besides Butter Knife), [Immutables][1], and also [android-apt][2].  Is it possible there is an incompatibility?  Also, I'm using the new Gradle 2.9.

[1]: https://github.com/immutables/immutables
[2]: https://bitbucket.org/hvisser/android-apt

**Comment by pushbit** [comment]
Some relevant stack trace.

    Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$PackageSymbol cannot be cast to javax.lang.model.element.TypeElement
        at pocketknife.internal.codegen.builder.BuilderProcessor.processIntentBuilder(BuilderProcessor.java:167)
        at pocketknife.internal.codegen.builder.BuilderProcessor.findAndParseTargets(BuilderProcessor.java:101)
        at pocketknife.internal.codegen.PocketKnifeProcessor.process(PocketKnifeProcessor.java:105)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)

**Comment by hansenji** [comment]
Yeah I have seen this before when I switched to Butter Knife 7.0 and binding. If there is an annotation without a proper import that caused a problem. The error is misleading because the APT tool runs before all the annotation dependencies are resolved.

**Comment by pushbit** [comment]
That's interesting.  So when you call `getElementsAnnotatedWith(IntentBuilder.class)`, it's giving you elements that are annotated with something other than `IntentBuilder`?  Is there a workaround or does the code need to be updated to be more defensive and make sure that it's dealing with a TypeElement before casting to it?

**Comment by hansenji** [comment]
I have added code to double check the annotation before using it I will release it in the next release.
