### ISSUE TITLE
Cache BundleBindings and IntentBindings

### ISSUE THREAD

**Issue by pushbit** [hansenji/pocketknife#14]
Have you considered caching `Binding` instances like how Butter Knife caches `ViewBinder` instances? (see `ButterKnife.findViewBinderForClass`)  It appears that, currently, every call to the methods in `PocketKnife` will instantiate a new `Binding` instance.  I think it would be great if this was only done once per process.

**Comment by hansenji** [comment]
I do this similar to Butter Knife and Dagger see line 204 of the file PocketKnife.java
`return CACHES.get(classLoader).get(name);`

**Comment by pushbit** [comment]
I believe that is only a cache for the `Class` instances.  On lines 134 and 173 new `Binding` instances from the `Class` constructor are instantiated.  In [ButterKnife:200][1], the `Binder` instances are cached (one per class) and are looked up each time `bind` is called instead of creating new instances.

[1]: https://github.com/JakeWharton/butterknife/blob/master/butterknife/src/main/java/butterknife/ButterKnife.java#L200

**Comment by hansenji** [comment]
I will take a look at it.

**Comment by hansenji** [comment]
So the creation of a binding class is not significant there is not a lot of baggage with the class so I am not going to cache the instance.
