### ISSUE TITLE
Error generating BundleAdapter for abstract class with generic parameter

### ISSUE THREAD

**Issue by TheIronMarx** [hansenji/pocketknife#20]
Using Pocketknife for state preservation, I've run into an issue when trying to `@SaveState` a variable in a class which has a generic parameter.

These should be the relevant bits
```
public abstract class Foo<V extends Baz> extends Bar<V> {
    protected V baz;

    @SaveState
    Stack<Integer> fooStack;
    // ... And so on 
```
Something like this generates an error in `Foo$$BundleAdapter`.
The class signature looks like this.
```public class Foo$$BundleAdapter<T extends Foo<V>> implements BundleBinding<T> {```

From there, the V generic can't be resolved as a symbol.

**Comment by vpratfr** [comment]
Same problem here :(

**Comment by vpratfr** [comment]
Most probably the fix will be done there: pocketknife-compiler/src/main/java/pocketknife/internal/codegen/binding/BundleBindingAdapterGenerator.java#L63

You add a generic parameter to represent the type of target object, but you do not add the generic parameters from the target object itself.

We get

```
public class GenericFragment$$BundleAdapter<T extends GenericFragment<DataT>>
       implements BundleBinding<T>
```

instead of:

```
public class GenericFragment$$BundleAdapter<DataT extends Serializable, T extends GenericFragment<DataT>>
       implements BundleBinding<T>
```

**Comment by hansenji** [comment]
Sorry I am deprecating this project due to Android now using Kotlin and libraries like https://github.com/Takhion/android-extras-delegates to replace this one.
