### ISSUE TITLE
Migrate project to Android Studio

### ISSUE THREAD

**Issue by vpratfr** [hansenji/pocketknife#21]
Android Studio is now stable and great to work with. Migrating your project to AS / Gradle would allow us to contribute. 

I wanted to try to fix #20 but I am not able to even compile the samples when I import the project under AS.

**Comment by hansenji** [comment]
Sorry I am deprecating this project due to Android now using Kotlin and libraries like https://github.com/Takhion/android-extras-delegates to replace this one.

**Comment by hansenji** [comment]
Sorry I am deprecating this project due to Android now using Kotlin and libraries like https://github.com/Takhion/android-extras-delegates to replace this one.
