### ISSUE TITLE
generated code doesn't account for periods in extra/argument keys

### ISSUE THREAD

**Issue by Phaedok** [hansenji/pocketknife#3]
I'm not sure if there are any other illegal characters that will cause this.
@InjectExtra(Intent.EXTRA_TITLE) will generate private static final String android.intent.extra.TITLE = "android.intent.extra.TITLE";
The variable name is picking up the periods and throwing errors.

**Comment by hansenji** [comment]
Fixed in commit d64a59d release as patch fix soon.
