### ISSUE TITLE
Use @Nullable instead of @NotRequired

### ISSUE THREAD

**Issue by renaudcerrato** [hansenji/pocketknife#9]
Hi there!

ButterKnife 7.0.0 has moved to Android's annotation `@Nullable` regarding optional fields. Since we have to add `@Nullable` anyway, that's redundant.

![@Nullable](http://i.imgur.com/miyXjvh.png)

**Comment by hansenji** [comment]
Not all of the types that can be saved to bundles and intents are nullable (primitives).

**Comment by renaudcerrato** [comment]
Too bad... That would keep your API consistent with ButterKnife, and using `@Nullable` on primitive only generate a lint warning and can be avoided by using `Double` instead of `double`, `Integer` instead of `int` and so on (which is a best practice anyway).
